const categoriasSeleccionadas = [
    "Accesorios",
    "Accesorios Almacenamiento",
    "Accesorios Audio/ Video / Música",
    "Accesorios Cámaras",
    "Accesorios Escritorio",
    "Accesorios Gaming",
    "Accesorios Escáners",
    "Accesorios Monitores y TV",
    "Accesorios Movilidad",
    "Accesorios Notebook/Tablet",
    "Accesorios POS Retail",
    "Accesorios Proyectores",
    "Accesorios Telefónicos",
    "Accesorios Impresión",
    "Dispositivos de Entrada / Salida",
    "Adaptadores Paralelo / Serial",
    "Adaptadores USB / FireWire",
    "Punto de Venta, AIDC y Código de Barras",
    "Accesorios AIDC Wireless",
    "Audio",
    "Audio / Video",
    "Equipo de Conferencia en Video, Audio y Web",
    "Automatización doméstica",
    "Bolsos y Mochilas",
    "Cables, Conectores y Adaptadores",
    "Cámaras",
    "Cartuchos de Limpieza",
    "Computadoras de Escritorio",
    "Computadoras Portátiles",
    "Controladores de disco",
    "Controles Juegos PC",
    "Discos de Estado Solido (SSD)",
    "Discos Duros",
    "Dispositivos con pantalla táctil",
    "Dispositivos de Switch",
    "Electrodomésticos",
    "Equipamiento de Energía",
    "Equipamiento para Rack",
    "Equipamiento Telefónico",
    "Impresoras, Plotters y Eq de Oficina",
    "Equipo de Oficina",
    "Escáner de Codigo de Barras Auto ID",
    "Escáners",
    "Floppy / Unidades de medios extraibles",
    "Fuentes de Poder",
    "Gabinetes de computadora y montaje",
    "Componentes",
    "Gabinetes para disco",
    "Garantías",
    "Impresoras Auto ID",
    "Impresoras Casa / Oficina",
    "Impresoras POS",
    "Media",
    "Memorias",
    "Memorias Flash",
    "Monitores",
    "Mouse",
    "Multifuncionales",
    "Pantallas de TV",
    "Periféricos POS",
    "Plotters",
    "Procesadores",
    "Protección Eléctrica",
    "Dispositivos de Video",
    "Proyectores",
    "Almacenamiento",
    "Dispositivos de Almacenamiento",
    "Red Unificada de Almacenamiento",
    "Redes",
    "Redes Inalámbricas",
    "Servicios y Garantías",
    "Servicios de Instalación",
    "Servidores",
    "Servidores para computadora",
    "Servidores RAS/Terminal/Device",
    "Seguridad Física",
    "Sistemas de Detección y Alarma contra incendios",
    "Sistemas SAN e Infraestructura",
    "Sonido Profesional y Entretenimiento",
    "Suministros",
    "Suministros de Impresión",
    "Suministros de Oficina",
    "Software",
    "SW Sistemas Operativos",
    "Switches y Hubs",
    "Tablets",
    "Tarjetas de Red",
    "Tarjetas de Sonido",
    "Tarjetas de Video y Captura",
    "Tarjetas Madre",
    "Teclados y Keypads",
    "Transceptores y Convertidores",
    "Video",
    "Consolas de Juegos",
    "Videojuegos",
    "Workstations"
];
  
module.exports = categoriasSeleccionadas