const categoriasSeleccionadas = [
    "Accesorios",
    "Accesorios y Componentes",
    "Accesorios Almacenamiento",
    "Accesorios Audio/ Video / Música",
    "Accesorios Cámaras",
    "Accesorios Escritorio",
    "Accesorios Gaming",
    "Accesorios Escáners",
    "Accesorios Monitores y TV",
    "Accesorios Movilidad",
    "Accesorios Notebook/Tablet",
    "Accesorios POS Retail",
    "Accesorios Proyectores",
    "Accesorios Telefónicos",
    "Accesorios Impresión",
    "Dispositivos de Entrada / Salida",
    "Adaptadores Paralelo / Serial",
    "Adaptadores USB / FireWire",
    "Punto de Venta, AIDC y Código de Barras",
    "Accesorios AIDC Wireless",
    "Audio",
    "Audio / Video",
    "Equipo de Conferencia en Video, Audio y Web",
    "Automatización doméstica",
    "Bolsos y Mochilas",
    "Cables, Conectores y Adaptadores",
    "Cámaras",
    "Cartuchos de Limpieza",
    "Computadoras de Escritorio",
    "Computadoras Portátiles",
    "Controladores de disco",
    "Controles Juegos PC",
    "Discos de Estado Solido (SSD)",
    "Discos Duros",
    "Dispositivos con pantalla táctil",
    "Dispositivos de Switch",
    "Electrodomésticos",
    "Equipamiento de Energía",
    "Equipamiento para Rack",
    "Equipamiento Telefónico",
    "Impresoras, Plotters y Eq de Oficina",
    "Equipo de Oficina",
    "Escáner de Codigo de Barras Auto ID",
    "Escáners",
    "Floppy / Unidades de medios extraibles",
    "Fuentes de Poder",
    "Gabinetes de computadora y montaje",
    "Componentes",
    "Gabinetes para disco",
    "Garantías",
    "Impresoras Auto ID",
    "Impresoras Casa / Oficina",
    "Impresoras POS",
    "Media",
    "Memorias",
    "Memorias Flash",
    "Monitores",
    "Mouse",
    "Multifuncionales",
    "Pantallas de TV",
    "Periféricos POS",
    "Plotters",
    "Procesadores",
    "Protección Eléctrica",
    "Dispositivos de Video",
    "Proyectores",
    "Almacenamiento",
    "Dispositivos de Almacenamiento",
    "Red Unificada de Almacenamiento",
    "Redes",
    "Redes Inalámbricas",
    "Servicios y Garantías",
    "Servicios de Instalación",
    "Servidores",
    "Servidores para computadora",
    "Servidores RAS/Terminal/Device",
    "Seguridad Física",
    "Sistemas de Detección y Alarma contra incendios",
    "Sistemas SAN e Infraestructura",
    "Sonido Profesional y Entretenimiento",
    "Suministros",
    "Suministros de Impresión",
    "Suministros de Oficina",
    "Software",
    "SW Sistemas Operativos",
    "Switches y Hubs",
    "Tablets",
    "Tarjetas de Red",
    "Tarjetas de Sonido",
    "Tarjetas de Video y Captura",
    "Tarjetas Madre",
    "Teclados y Keypads",
    "Transceptores y Convertidores",
    "Video",
    "Consolas de Juegos",
    "Videojuegos",
    "Workstations",
    "Drones",
    "Servicios de envío",
    "Software Gestión de Datos",
    "Juguetes",
    "Cómputo y Consolas",
    "Videovigilancia",
    "Thin Clients y Terminales",
    "Terminales móviles AIDC",
    "Teatro en casa",
    "Tablets - Notebook 2 en 1",
    "SW Soluciones de Negocio",
    "SW Seguridad",
    "SW Productividad Office",
    "SW Imagen y Firma Digital",
    "SW Entretenimiento",
    "Suministros POS Retail y Auto ID",
    "Software Virtualización",
    "Software Gestionamiento IT",
    "Software Almacenamiento",
    "Sistemas telefónicos, teléfonos y componentes",
    "Sistemas NAS",
    "Servicios Profesionales de Proveedor",
    "Servicios Help Desk",
    "Seguridad de redes",
    "Routers y Componentes",
    "Pantallas para Proyección",
    "Office Productivity Software",
    "Línea Blanca",
    "Lectores RFID",
    "Lectores POS",
    "Garantías, Pago de Servicio y Contratos",
    "Electrodomésticos grandes (large appliances)",
    "Dispositivos Señaladores y Pizarras",
    "Dispositivos de respaldo",
    "Dispositivos de Comunicación Móvil",
    "Curso de Aplicación",
    "Control de Acceso fisico",
    "AIDC/POS Software"
];
  
module.exports = categoriasSeleccionadas