const marcasSeleccionadasIngram = [
    "Acer",
    "Adesso",
    "Apple",
    "Adata",
    "Aruba",
    "ASUS",
    "Axis",
    "Acteck",
    "Barco",
    "Balam Rush",
    "BenQ",
    "Bixolon",
    "Brother",
    "Buffalo",
    "Canon",
    "CDP",
    "Comercializadora de Valor Agregado",
    "CyberPower",
    "Elo",
    "Epson",
    "GoPro",
    "Hisense",
    "Honeywell",
    "HP",
    "IOTZONE DC POS",
    "Kingston",
    "Koblenz",
    "Lenovo",
    "LG",
    "Linksys",
    "Logitech",
    "Microsoft",
    "Perfect Choice",
    "Naceb",
    "PERFORMANCE DESIGNED",
    "Plantronics",
    "Razer",
    "Samsung",
    "Schneider Electric",
    "StarTech",
    "Xiaomi",
    "Nexxt Home",
    "PlayStation"
  ];
  
module.exports = marcasSeleccionadasIngram